version: "3"

services:

  cron-job:
    build: ./
    image: image-live-now-job
    container_name: live_now_job_container
    env_file:
      # - ./env/live_now_job.env
      # - .env # local
      - ../../env/live_now_job.env
    volumes:
      - type: bind
        source: ../../log/live_now_cron
        target: /var/log/cron
      - type: bind
        source: .
        target: /app/live-now-job
        

